apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assessment2
  template:
    metadata:
      labels:
        app: assessment2
    spec:
      containers:
      - name: assessment2
        image: prankumar313/assessment2:latest
        ports:
        - containerPort: 80
